services:
  nginx:
    image: nginx:1.23.4
    container_name: laravel_vue_nginx
    ports:
      - "3000:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      # ↓ Nginx にフロントコードをマウントする必要はありません（削除）
      # - ./client:/var/www/web
    depends_on:
      - api
      - client
    restart: always

  api:
    build: ./docker/api
    container_name: laravel_vue_api
    ports:
      - "9000:9000"
    volumes:
      - ./api:/var/www/api
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: secret
    expose:
      - 9000
    depends_on:
      - db
    restart: always

  client:
    platform: linux/amd64
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    container_name: laravel_vue_client
    # ホットリロード用途に “コードのみ” をマウント。
    # node_modules は匿名ボリュームでコンテナ側を保護（ホストで上書きしない）
    volumes:
      - ./client:/var/www/client
      - /var/www/client/node_modules
    # 外部公開ポートは不要（Nginx が 3000 を受ける）
    restart: always

  db:
    image: mysql:8.0
    container_name: laravel_vue_db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    restart: always

volumes:
  dbdata:
