services:
  nginx:
    image: nginx:1.23.4
    container_name: laravel_vue_nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./api:/var/www/api:ro
    depends_on:
      - api
      - client
    restart: always

  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    container_name: laravel_vue_api
    ports:
      - "9000:9000"
    volumes:
      - ./api:/var/www/api
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: secret
    expose:
      - 9000
    depends_on:
      - db
    restart: always

  client:
    command: sh -lc "npm ci || npm i && npm run dev"
    platform: linux/amd64
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    container_name: laravel_vue_client
    volumes:
      - ./client:/var/www/client
      - /var/www/client/node_modules
    restart: always

  db:
    image: mysql:8.0
    container_name: laravel_vue_db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    restart: always

volumes:
  dbdata:
